ORG 00H
	MOV R0,#40H//SEARCHING OBJECT
	MOV R1,#30H//SEQUENCE OF DATA
	MOV R2,#0AH//COUNTER REGISTERS
	CLR A
	LOOP:MOV A,@R1
		MOV B,@R0
		CJNE A,B,SKIP
		MOV P0,#00H
		SKIP:MOV P0,#0FFH
		INC R1
		DJNZ R2,LOOP
		END